### ISSUE TITLE
Failed to copy the file `uploads/templates/drawed_grid/IMAGE_NAME.jpg` to the necessary target directory `uploads/templates/drawed_grid_text/3`.

### ISSUE THREAD

**Issue by melliiii** [Sebbo94BY/teamspeak-dynamic-banner#164]
**Environment**
- TeamSpeak Dynamic Banner Version: 0.6.0
- Operating System: Windows running your docker-compose.yml in Docker version 24.0.6, build ed223bc with wsl2
- Web Server: nginx version 1.25.1
- PHP: v8.2.10
- Database: mysql v8.0.33

**Describe the bug**
Hey there, 
im running your software in docker because it was the easiest to set up and my install on debian 12 failed before i got to see the beautiful dashboard.

When i add a template to a banner i get an error screen showing me [this](https://flareapp.io/share/J7oeWrkm) and basically tells me it cant copy the upload file to where it needs to be. 

Highlighted Code on Error Page:
```php
if (! Storage::disk('public')->copy($source_file_path, $this->target_directory.'/'.$this->template->filename)) {
  throw new Exception("Failed to copy the file `$source_file_path` to the necessary target directory `$this->target_directory`.");
} 
``` 

if i then reload the site it will give me the template on the banner but it will not show the image i selected. you can imagine going forward with this results it a big red error box on the banner configurator. even copying it by hand via the `docker-compose exec -it backend bash ` console doesnt result in it working.

the system status page shows all green for me. The whole page seems to be really slow for me, loading the next page takes about 10 seconds, but it is the same as my install on a linux VM.
This log seems to be repeating every few seconds: https://hastebin.skyra.pw/jibuwacuca.yaml

**Screenshots**
[Systemstatus Page](https://prnt.sc/5j9_1Ml0xgVU)
[Adding Template to Banner](https://prnt.sc/1NOS7-nB6MxU)
[Error Page](https://prnt.sc/-Qb1P0O-RNm-)

I firmly believe its not your fault that its running slow and throws errors but its something on my side, which is why i tried installing in a docker container but it didnt solve my issue unfortunatly.

**Comment by Sebbo94BY** [comment]
Hey @melliiii,
Thanks for your interest in this project. :-)

First of all: The here included **Docker setup is only for local development and testing purposes.** The setup is not optimized for the production use due to a slow network setup (I still don't get the reason for this) and especially as some functionalities are not working as they should in production due to the different Docker containers (known and expected behaviour).

Also see https://github.com/Sebbo94BY/teamspeak-dynamic-banner/blob/main/docs/CONTRIBUTE.md, if you're interested in a contribution. :-)

For the production use, it's recommend to follow the installation instructions: https://github.com/Sebbo94BY/teamspeak-dynamic-banner/blob/main/docs/INSTALLATION.md

Then everything will work as expected and the performance will be also much better. :-)

I can support you via e. g. a screensharing session with the setup, if you're interested. This would also help the project to further improve it in order that everyone is better able to set it up by their own.

The reported issue seems to be a generic issue. I'll try to reproduce this and then I can fix it, if it's a code issue.

**Comment by Sebbo94BY** [comment]
Ok, I've now destroyed my local Docker test setup and deleted this repository locally.

Afterwards, I've downloaded the repository again and followed the [CONTRIBUTE.md](https://github.com/Sebbo94BY/teamspeak-dynamic-banner/blob/main/docs/CONTRIBUTE.md) instructions 1:1. At the end I had a fresh installation of this application and the installer with the requirements page was shown. I've clicked through this installer wizard to set up the initial super user.

Then I've added a new instance, uploaded a template (image) and added a new banner. The banner, I've added the recently uploaded template. Everything worked as expected. I didn't faced any issues or saw any errors in the logs.

So from the application side, everything is properly implemented and working as expected. Maybe your `laravel/public/` directory had incorrect permissions or your jobs are getting executed with the wrong user and thus wrong permissions.

In best case, the jobs are running under the same user as the web server does - usually this is `www-data`.

---

Ok, thanks for your update. Let me know, if I can support you. :-)

Yeah, apache is by default a bit slower as it always checks for e. g. `.htaccess` files at each web request, what nginx doesn't, but you can improve the apache performance by changing a few settings to avoid these checks for example.

Also PHP FPM can improve the performance compared to apache (PHP) MPM. But that's totally up to you, if you want to use apache or nginx and MPM or FPM. This project should be fast on both setups. :)

**Comment by melliiii** [comment]
okay i got the problem i had sorted out, turns out you gotta also start your services :)

now another problem arised, as i dont have any idea how to configure nginx with laravel apps :/ 

i got the public folder in /var/www/teamspeak-dynamic-banner/laravel/public/ and i dont think im well enough informed about how nginx works to get this working without problems

**Comment by Sebbo94BY** [comment]
You can find an example nginx vHost configuration here: https://github.com/Sebbo94BY/teamspeak-dynamic-banner/blob/main/docker/nginx/localhost.conf

`root` must be set to `/var/www/teamspeak-dynamic-banner/laravel/public` in your case.

The `fastcgi_pass` defines where nginx should forward your PHP requests at - in this case to PHP FPM. This can be a TCP connection like `127.0.0.1:9000` or a socket like `unix:/var/run/php-fpm.sock`. This depends on what you have configured in your PHP FPM `listen` configuration (https://www.php.net/manual/en/install.fpm.configuration.php).

**Comment by melliiii** [comment]
okay i added a this config file: 

/etc/nginx/sites-available
```
server {
         listen 80;
         listen [::]:80 ipv6only=on;

         # Log files for Debugging
         access_log /var/log/nginx/laravel-access.log;
         error_log /var/log/nginx/laravel-error.log;

         # Webroot Directory for Laravel project
         root /var/www/teamspeak-dynamic-banner/laravel/public;
         index index.php index.html index.htm;

         # Your Domain Name
         server_name localhost;

         location / {
                 try_files $uri $uri/ /index.php?$query_string;
         }

         # PHP-FPM Configuration Nginx
         location ~ \.php$ {
                 try_files $uri =404;
                 fastcgi_split_path_info ^(.+\.php)(/.+)$;
                 fastcgi_pass unix:/run/php/php7.2-fpm.sock;
                 fastcgi_index index.php;
                 fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                 include fastcgi_params;
         }
 }
``` 

and linked it with `ln -s /etc/nginx/sites-available/teamspeak-dynamic-banner /etc/nginx/sites-enabled/`
ran `nginx -t`, got ok and restarted the service, still cant reach the site :/

**Comment by Sebbo94BY** [comment]
First of all: This application requires PHP 8.1 or 8.2. Your here configured socket seems to be a PHP 7.2 - this won't work at all at the end. :-)

Please ensure, that your `server_name` is correct and matches your domain and also ensure, that you use a PHP 8.1 or 8.2 PHP in `fastcgi_pass`.

Also ensure, that your FPM is running: `systemctl status php8.1-fpm.service`

**Comment by melliiii** [comment]
thank you, i changed the following:
`server_name _;` and changed the typo from 7.2 to 8.2 and now i dont get 502 Bad Gateway anymore ;3

`systemctl status php8.2-fpm.service` gives me a green light and i got the setup screen which showed me 2 warnings (ssh2 and upload file size, which i both fixed). now i tried adding an instance, and get the 500 Server Error screen after pressing save. the inputs i gave should be correct

**Comment by Sebbo94BY** [comment]
If you got a HTTP 500 error, you should see an error message in either the application, its logs (`laravel/storage/logs/`) or in the nginx / PHP logs.

But it sounds like as the permissions aren't correct. Please ensure, that your web server has enough permissions to read and write the application files. All files (in the `laravel/` directory) should be owned by the web server user - usually `www-data`.

Yeah, that's what I said. The Docker setup is buggy. I've debugged the performance issues in Docker, but I didn't figured out yet what's the root cause. :sweat_smile:

**Comment by melliiii** [comment]
permissions seem fine:
```
melli@ts3banner:~$ ls -la /var/www/teamspeak-dynamic-banner/laravel/
total 232
drwxr-xr-x 16 www-data www-data     32 Sep 26 15:07 .
drwxr-xr-x  8 www-data www-data     12 Sep 26 14:34 ..
drwxr-xr-x  3 www-data www-data      3 Sep 26 14:34 .config
-rw-r--r--  1 www-data www-data    258 Sep 26 14:34 .editorconfig
-rw-r--r--  1 www-data www-data    748 Sep 26 14:55 .env
-rw-r--r--  1 www-data www-data    682 Sep 26 14:34 .env.example
-rw-r--r--  1 www-data www-data    270 Sep 26 14:34 .env.testing
-rw-r--r--  1 www-data www-data    181 Sep 26 14:34 .gitattributes
-rw-r--r--  1 www-data www-data    311 Sep 26 14:34 .gitignore
drwxr-xr-x  3 www-data www-data      3 Sep 26 14:34 .local
-rw-r--r--  1 www-data www-data   5493 Sep 26 14:34 .php-cs-fixer.php
-rw-r--r--  1 www-data www-data   4158 Sep 26 14:34 README.md
drwxr-xr-x  8 www-data www-data      8 Sep 26 14:34 app
-rw-r--r--  1 www-data www-data   1686 Sep 26 14:34 artisan
drwxr-xr-x  3 www-data www-data      4 Sep 26 14:34 bootstrap
-rw-r--r--  1 www-data www-data   2265 Sep 26 14:34 composer.json
-rw-r--r--  1 www-data www-data 355721 Sep 26 14:34 composer.lock
drwxr-xr-x  2 www-data www-data     19 Sep 26 14:34 config
drwxr-xr-x  5 www-data www-data      6 Sep 26 14:34 database
-rw-r--r--  1 www-data www-data     88 Sep 26 15:07 dump.rdb
drwxr-xr-x  3 www-data www-data      3 Sep 26 14:34 lang
drwxr-xr-x 45 www-data www-data     46 Sep 26 14:35 node_modules
-rw-r--r--  1 www-data www-data  34635 Sep 26 14:35 package-lock.json
-rw-r--r--  1 www-data www-data    498 Sep 26 14:34 package.json
-rw-r--r--  1 www-data www-data    837 Sep 26 14:34 phpunit.xml
drwxr-xr-x  5 www-data www-data      9 Sep 26 15:08 public
drwxr-xr-x  6 www-data www-data      6 Sep 26 14:34 resources
drwxr-xr-x  2 www-data www-data      6 Sep 26 14:34 routes
drwxr-xr-x  5 www-data www-data      5 Sep 26 14:34 storage
drwxr-xr-x  4 www-data www-data      6 Sep 26 14:34 tests
drwxr-xr-x 35 www-data www-data     36 Sep 26 14:35 vendor
-rw-r--r--  1 www-data www-data    388 Sep 26 14:34 vite.config.js
``` 

i dont have any new logs apart from those from the installation in `/var/www/teamspeak-dynamic-banner/laravel/storage/logs/laravel.log` 

`/var/log/nginx/laravel-error.log` and `/var/log/nginx/error.log` dont have any new entries 🤔

**Comment by melliiii** [comment]
Thanks for not giving up on me xd i know im really not good with all this stuff yet :/

**Comment by Sebbo94BY** [comment]
Are the permissions are also correct inside the `storage/` directory? Laravel automatically creates there subdirectories to manage the caches. Your issue sounds like as there is a folder with incorrect permissions, which causes the application to fail writing files and thus you get a HTTP 500 error.

**Comment by melliiii** [comment]
i executed `sudo chown -R www-data:www-data /var/www/` and restarted nginx and it doesnt change anything 🤔

**Comment by melliiii** [comment]
i found a problem, my redis-server crashed again, which is why i couldnt access the dashboard... still doesnt change anything about being unable to create a instance and i still get error 500 when i try to

**Comment by melliiii** [comment]
Cant tell you how but now it works O.o things if done is setting the max file upload size in the correct php.ini (etc/php/8.2/fpm/php.ini) and installing the apt package php8.2-ssh2. also restarting the fpm service `sudo systemctl restart php8.2-fpm` after doing anything.

**Comment by melliiii** [comment]
i will stop trying for today, ive been on this for 7 hours straight now and im kinda getting tired, but thank you for your help so far, im optimistic we can get it running :)

**Comment by Sebbo94BY** [comment]
I've edited your `.env` to remove the secret `APP_KEY`. However, since you published it here, you should also change it in your production application as it's a sensitive secret. It's used for de- and encrypting things in the application, so if your database gets stolen, this key is required to decrypt a few things like the ServerQuery passwords.

But please be aware, that you need to reset your users password afterwards (e. g. via forgot password) and that you need to re-save your ServerQuery password(s), if you have already saved any.

---

Ok, so the permissions should be fine, good.

> is `laravel/storage/app/public/` supposed to be empty?

Yes, this project is currently not really using this storage - it's only used for app caching, but the public folder is not used.

> i cant find any new error logs, neither nginx, php or laravel related.

This is strange, because a HTTP 500 error should be always logged somewhere.

Have you executed all commands from the [INSTALLATION](https://github.com/Sebbo94BY/teamspeak-dynamic-banner/blob/main/docs/INSTALLATION.md) guide? And did they all succeed or did any of them report an error? If you're unsure, you can simply re-run all of these commands (EXCEPT OF `php artisan key:generate` - this will generate a new application key, which is used for the encryption) - this will not break anything.

If the Redis server is not available, the entire application should still work. It will only not show any available variables and on the banner, it can respectively not replace the variables with the actual values. But it should not cause any unreachable pages or HTTP 500 errors.

`sudo systemctl enable redis-server.service` should enable the auto-start. :-)

Since the file does not exist after you've tried to upload it, it seems like as the file upload failed.

It could be also, that PHP FPM terminates and restarts due to whatever reason. Have you checked the PHP FPM logs for any restarts / kills?

**Comment by Sebbo94BY** [comment]
I've just released a new version: https://github.com/Sebbo94BY/teamspeak-dynamic-banner/releases/tag/0.6.1

Especially the checkbox for the ServerQuery encryption might be useful for you. Before, the code automatically tried to establish first a SSH connection for the ServerQuery connection - if this failed, it tried the old RAW method. You can now force this behaviour by dis-/enabling this new checkbox.

**Comment by melliiii** [comment]
i just updated to your new version, really like it 👍🏻 
yeah i think security wasnt really someting i had in the back of my mind when i set this machine up xd good thing its just a VM and will be put down when i get it running completely and i will then reinstall everything the right way ^^ but until we get it running this thing will do. Didnt know that the key was for encryption :v 

As part of the Update i reran all the commands, i followed your update guide to the letter, except for the restart of the supervisor, as i dont have that set up yet.

i made my way to the `/etc/php/8.2/fpm/php-fpm.conf` file and added the error log to `/var/log/php8.2-fpm.log`, created the file with `touch /var/log/php8.2-fpm.log` and ran `chmod 666 /var/log/php8.2-fpm.log` (all with root privileges of course) and look at that, i get an error log that goes back to when i installed it. The file did not exist until i created it and i got this log output:

```
[27-Sep-2023 05:40:46] NOTICE: Terminating ...
[27-Sep-2023 05:40:46] NOTICE: exiting, bye-bye!
[27-Sep-2023 05:40:46] NOTICE: fpm is running, pid 9937
[27-Sep-2023 05:40:46] NOTICE: ready to handle connections
[27-Sep-2023 05:40:46] NOTICE: systemd monitor interval set to 10000ms
``` 
(ignore the wrong timestamps, already reset my timezone)

i thought i had a reason as to why it is so i set the log level to debug, let the log spam my console with `tail -f /var/log/php8.2-fpm.log` but i seem to not really get any usefull output at all. Weird

Also i checked my nginx log configuration with `find /etc/nginx -name '*.conf' | xargs grep -i log` and it gave me my 2 log files in /var/log/nginx/ so the Error 500 is not handled by nginx but by your code which could be why its not being shown in my log file, at least thats what i understand from [this stackoverflow post](https://serverfault.com/questions/579919/nginx-1-2-1-how-to-analyse-500-internal-server-error)

**Comment by melliiii** [comment]
Well looks like i really need to pay more attention, setting up the supervisor correctly seems to be very important and redoing it solved my issue, i can now edit banners :D

**Comment by Sebbo94BY** [comment]
Great. I'm happy, that it's working for you now.

Cool. Looks awesome!
