### ISSUE TITLE
[Feature] GIF Support for Banners

### ISSUE THREAD

**Issue by melliiii** [Sebbo94BY/teamspeak-dynamic-banner#171]
**Describe the solution you'd like**
Support for adding GIF's as Banner Templates

**Additional context**
I found out that you could actually add GIFs in the Banner URL in Teamspeak and now my community wont stop talking about animated banners so GIF Support for this software would be really nice :3

**Comment by Sebbo94BY** [comment]
Oh, yeah. That would be definitley an interesting feature.

I'll check, if we can add a GIF support based on all functionalities and what we have to change / adjust for it. :-)

**Comment by melliiii** [comment]
thank you :)

**Comment by Sebbo94BY** [comment]
I've took a look at this feature request and tested a few things.

In general, we can add support for GIF files (Mime type `image/gif`).

Unfortunately, animated GIF files would currently break as you would always only get the first frame of the animated GIF. I have currently no solution, how we can draw lines (for the grid system) and write text on animated GIFs, so that they contain afterwards the lines and texts and are still animated.

If you (or anyone else) have any idea how to solve this issue, let me know. it.

I've also already asked the Stackoverflow community since my research via Google didn't return anything helpful: https://stackoverflow.com/questions/77208057/draw-lines-and-write-text-on-animated-gif-image-using-php

**Comment by Sebbo94BY** [comment]
@melliiii I've successfully added support for (animated) GIFs. :-)

Please note, that you need to install `ffmpeg` on your Linux system to enable the GIF support. There is also a new check on the System Status page.
